--
-- Register lib_materials ecosystems
--
-- Define constants that can be used in csv
local heights = {
	ocean_depth = gal.mapgen.ocean_depth,
	beach_depth = gal.mapgen.beach_depth,
	sea_level = gal.mapgen.sea_level,
	beach = gal.mapgen.maxheight_beach,
	coastal = gal.mapgen.maxheight_coastal,
	lowland = gal.mapgen.maxheight_lowland,
	shelf = gal.mapgen.maxheight_shelf,
	highland = gal.mapgen.maxheight_highland,
	mountain = gal.mapgen.maxheight_mountain,
	snow_min = gal.mapgen.minheight_snow,
	snow_max = gal.mapgen.maxheight_snow,
	--strato = gal.maxheight_strato,
	strato = 31000,
}


local function read_node_str(node_str)
	if #node_str > 0 then
		local node, count = node_str:match("([^%s]+)%s*(%d*)")
		return node, tonumber(count) or 1
	end
end

if minetest.get_mapgen_setting("mg_name") == "v5" or minetest.get_mapgen_setting("mg_name") == "v7"
	or minetest.get_mapgen_setting("mg_name") == "flat" or minetest.get_mapgen_setting("mg_name") == "fractal"
	or minetest.get_mapgen_setting("mg_name") == "carpathian" or minetest.get_mapgen_setting("mg_name") == "valleys" then

	
	for i, ecosystem in ipairs(gal.lib.csv.read("|", gal.path .. "/" .. gal.ecosystem_data_file .. ".csv")) do
		local oretype, orename, wherein, threshold, ymin, ymax, biome = unpack(ecosystem)
		--minetest.log(oretype .. ", " .. orename .. ", " .. wherein .. ", " .. threshold .. ", " .. ymin .. ", " .. ymax .. ", " .. biome)

		-- Parse node names: transform empty strings into nil and separate node and count
		--b = read_node_str(b)
		--local c1, c2 = read_node_str(c)

		local spread_val = 2^(tonumber(threshold) * 10)
		----local ore_seed = math.random(1, spread_val)
		--local ore_seed = tonumber(minetest.sha1(biome .. "_" .. orename))
		local ore_seed = i

		--gal.add_oredef(orename, ore_seed)

		if oretype == "dirt" then
			minetest.register_ore({
				ore_type = "sheet",
				ore = "gal:" .. orename,
				wherein = "gal:" .. wherein,
				clust_size = 8,
				y_min = tonumber(ymin) or (heights[ymin] - gal.mapgen.biome_vertical_blend),
				y_max = tonumber(ymax) or (heights[ymax] + gal.mapgen.biome_vertical_blend),
				noise_threshold = tonumber(threshold),
				noise_params = {
					offset = 0,
					scale = 1,
					spread = {x = 128, y = 128, z = 128},
					seed = ore_seed,
					octaves = 5,
					persist = 0.60
				},
				column_height_min = (gal.mapgen.biome_vertical_range / 2) + gal.mapgen.biome_vertical_blend,  --1
				column_height_max = gal.mapgen.biome_vertical_range + (gal.mapgen.biome_vertical_blend * 2),
				column_midpoint_factor = 0.5,
				biomes = biome or nil
			})
		elseif oretype == "fungi" then
			minetest.register_ore({
				ore_type = "sheet",
				ore = "gal:" .. orename,
				wherein = "gal:" .. wherein,
				clust_size = (tonumber(threshold) * 10),
				y_min = tonumber(ymin),
				y_max = tonumber(ymax),
				noise_threshold = tonumber(threshold),
				noise_params = {
					offset = 0,
					scale = 1,
					spread = {x = spread_val, y = spread_val, z = spread_val},
					seed = ore_seed,
					octaves = 5,
					persist = 0.60
				},
					column_height_min = 1,
					column_height_max = gal.mapgen.biome_vertical_range,
					column_midpoint_factor = 0.5,
				biomes = biome or nil
			})
		elseif oretype == "blob" then

			minetest.register_ore({
				ore_type = "sheet",
				ore = "gal:" .. orename,
				wherein = "gal:" .. wherein,
				clust_size = 8,
				y_min = tonumber(ymin) or (heights[ymin] - gal.mapgen.biome_vertical_blend),
				y_max = tonumber(ymax) or (heights[ymax] + gal.mapgen.biome_vertical_blend),
				noise_threshold = tonumber(threshold),
				noise_params = {
					offset = 0,
					scale = 1,
					spread = {x = 128, y = 128, z = 128},
					seed = ore_seed,
					octaves = 5,
					persist = 0.60
				},
				column_height_min = (gal.mapgen.biome_vertical_range / 2) + gal.mapgen.biome_vertical_blend,  --1
				column_height_max = gal.mapgen.biome_vertical_range + (gal.mapgen.biome_vertical_blend * 2),
				column_midpoint_factor = 0.5,
				biomes = biome or nil
			})

	--
			-- minetest.register_ore({
				-- ore_type         = "blob",
				-- ore              = "gal:" .. orename,
				-- wherein          = "gal:" .. wherein,
				-- --clust_scarcity   = 4 * 4 * 4,
				-- clust_scarcity   = (tonumber(threshold) * 10) * (tonumber(threshold) * 10) * (tonumber(threshold) * 10),
				-- --clust_num_ores = 8,
				-- clust_num_ores = 128,
				-- --clust_size       = 6,
				-- clust_size       = (tonumber(threshold) * 10),
				-- y_min = tonumber(ymin),
				-- y_max = tonumber(ymax),
				-- noise_params     = {
					-- offset = 0,
					-- scale = 1,
					-- spread = {x = 128, y = 128, z = 128},
					-- seed = ore_seed,
					-- octaves = 5,
					-- persist = 0.60
					-- -- offset = 0.35,
					-- -- scale = 0.2,
					-- -- --spread = {x = 5, y = 5, z = 5},
					-- -- spread = {x = spread_val, y = spread_val, z = spread_val},
					-- -- --seed = -316,
					-- -- seed = ore_seed,
					-- -- octaves = 1,
					-- -- persist = 0.5
				-- },
				-- biomes = biome or nil,
				-- random_factor = 1.0
			-- })
	--

		elseif oretype == "" then

		else

		end
	end
end

local biome_list = {
	"hot_humid",
	"hot_semihumid",
	"hot_temperate",
	"hot_semiarid",
	"hot_arid",
	"warm_humid",
	"warm_semihumid",
	"warm_temperate",
	"warm_semiarid",
	"warm_arid",
	"temperate_humid",
	"temperate_semihumid",
	"temperate_temperate",
	"temperate_semiarid",
	"temperate_arid",
	"cool_humid",
	"cool_semihumid",
	"cool_temperate",
	"cool_semiarid",
	"cool_arid",
	"cold_humid",
	"cold_semihumid",
	"cold_temperate",
	"cold_semiarid",
	"cold_arid",
}

local n_list = {
	"n1",
	"n2",
	"n3",
	"n4",
	"n5",
	"n6",
	"n7",
	"n8",
	"n9",
	"n10",
	"n11",
	"n12",
	"n13",
	"n14",
	"n15",
	"n16",
}

local eco_list = {
	hot_humid = {
		-- --loess		= {"", "dirt_loess_with_grass_hot_humid","dirt_loess","stone_basalt_01",},
		-- --swamp		= {"", "dirt_black_with_grass_hot_humid","dirt_black","stone_basalt_01",},
		n9	= {name="n9",		desc="black",	top="dirt_black_with_litter_rainforest",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_litter_rainforest",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_litter_rainforest",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_litter_rainforest",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_litter_rainforest",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat_with_litter_rainforest",			fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01_with_litter_rainforest",		fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_hot_humid_pale",		fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_hot_humid_pale",		fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_hot_humid_pale",		fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_litter_rainforest",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	hot_semihumid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_hot_semihumid",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_hot_semihumid",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_hot_semihumid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_hot_semihumid",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_hot_semihumid",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_hot_semihumid_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_hot_semihumid_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_hot_semihumid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_hot_semihumid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	hot_temperate = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_hot_temperate",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_hot_temperate",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_hot_temperate",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_hot_temperate",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_hot_temperate",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_hot_temperate_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_hot_temperate_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_hot_temperate_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_hot_temperate",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_grass_dry",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_grass_dry",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	hot_semiarid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_hot_semiarid",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_hot_semiarid",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_hot_semiarid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_hot_semiarid",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_hot_semiarid",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_hot_semiarid_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_hot_semiarid_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_hot_semiarid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_hot_semiarid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_grass_dry",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_grass_dry",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	hot_arid = {
		n9	= {name="n9",		desc="black",	top="stone_sandstone_gravel",					fill="stone_sandstone_gravel",			stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="stone_sandstone_white_gravel",				fill="stone_sandstone_white_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey",								fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy",								fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="desert",	top="sand_desert",								fill="sand_desert",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="white",	top="sand_white",								fill="sand_white",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="stone_sandstone_desert_gravel",			fill="stone_sandstone_desert_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="stone_desert_gravel",						fill="stone_desert_gravel",				stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_hot_semiarid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_hot_semiarid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_dry",									fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dried",								fill="dirt_dried",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	warm_humid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_warm_humid",			fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_warm_humid",			fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_warm_humid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_warm_humid",			fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_warm_humid",			fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_warm_humid_pale",		fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_warm_humid_pale",		fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_warm_humid_pale",		fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_warm_humid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	warm_semihumid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_warm_semihumid",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_warm_semihumid",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_warm_semihumid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_warm_semihumid",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_warm_semihumid",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_warm_semihumid_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_warm_semihumid_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_warm_semihumid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_warm_semihumid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	warm_temperate = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_warm_temperate",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_warm_temperate",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_warm_temperate",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_warm_temperate",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_warm_temperate",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_warm_temperate_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_warm_temperate_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_warm_temperate_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_warm_temperate",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_grass_dry",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_grass_dry",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	warm_semiarid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_warm_semiarid",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_warm_semiarid",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_warm_semiarid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_warm_semiarid",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_warm_semiarid",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_warm_semiarid_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_warm_semiarid_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_warm_semiarid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_warm_semiarid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_grass_dry",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_grass_dry",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	warm_arid = {
		n9	= {name="n9",		desc="black",	top="stone_sandstone_gravel",					fill="stone_sandstone_gravel",			stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="stone_sandstone_white_gravel",				fill="stone_sandstone_white_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey",								fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy",								fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="desert",	top="sand_desert",								fill="sand_desert",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="white",	top="sand_white",								fill="sand_white",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="stone_sandstone_desert_gravel",			fill="stone_sandstone_desert_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="stone_desert_gravel",						fill="stone_desert_gravel",				stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_warm_semiarid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_warm_semiarid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_dry",									fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dried",								fill="dirt_dried",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	temperate_humid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_temperate_humid",			fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_temperate_humid",			fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_temperate_humid",			fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_temperate_humid",			fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_temperate_humid",			fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_temperate_humid_pale",		fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_temperate_humid_pale",		fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_temperate_humid_pale",		fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_temperate_humid",			fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	temperate_semihumid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_temperate_semihumid",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_temperate_semihumid",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_temperate_semihumid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_temperate_semihumid",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_temperate_semihumid",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_temperate_semihumid_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_temperate_semihumid_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_temperate_semihumid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_temperate_semihumid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	temperate_temperate = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_temperate_temperate",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_temperate_temperate",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_temperate_temperate",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_temperate_temperate",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_temperate_temperate",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_temperate_temperate_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_temperate_temperate_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_temperate_temperate_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_temperate_temperate",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_grass_dry",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_grass_dry",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	temperate_semiarid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_temperate_semiarid",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_temperate_semiarid",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_temperate_semiarid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_temperate_semiarid",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_temperate_semiarid",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_temperate_semiarid_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_temperate_semiarid_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_temperate_semiarid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_temperate_semiarid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_grass_dry",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_grass_dry",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	temperate_arid = {
		n9	= {name="n9",		desc="black",	top="stone_sandstone_gravel",					fill="stone_sandstone_gravel",			stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="stone_sandstone_white_gravel",				fill="stone_sandstone_white_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey",								fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy",								fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="desert",	top="sand_desert",								fill="sand_desert",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="white",	top="sand_white",								fill="sand_white",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="stone_sandstone_desert_gravel",			fill="stone_sandstone_desert_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="stone_desert_gravel",						fill="stone_desert_gravel",				stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_temperate_semiarid_pale",	fill="dirt_red",					stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_temperate_semiarid",	fill="dirt_coarse",					stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_dry",									fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dried",								fill="dirt_dried",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cool_humid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_cool_humid",			fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_cool_humid",			fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_cool_humid",			fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_cool_humid",			fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_cool_humid",			fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_cool_humid_pale",		fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_cool_humid_pale",		fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_cool_humid_pale",		fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_cool_humid",			fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cool_semihumid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_cool_semihumid",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_cool_semihumid",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_cool_semihumid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_cool_semihumid",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_cool_semihumid",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_cool_semihumid_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_cool_semihumid_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_cool_semihumid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_cool_semihumid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cool_temperate = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_cool_temperate",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_cool_temperate",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_cool_temperate",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_cool_temperate",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_cool_temperate",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_cool_temperate_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_cool_temperate_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_cool_temperate_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_cool_temperate",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_grass_dry",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_grass_dry",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cool_semiarid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_grass_cool_semiarid",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_grass_cool_semiarid",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_grass_cool_semiarid",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_grass_cool_semiarid",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_grass_cool_semiarid",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_grass_cool_semiarid_pale",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_grass_cool_semiarid_pale",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_cool_semiarid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_cool_semiarid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_grass_dry",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_grass_dry",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cool_arid = {
		n9	= {name="n9",		desc="black",	top="stone_sandstone_gravel",					fill="stone_sandstone_gravel",			stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="stone_sandstone_white_gravel",				fill="stone_sandstone_white_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey",								fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy",								fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="desert",	top="sand_desert",								fill="sand_desert",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="white",	top="sand_white",								fill="sand_white",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="stone_sandstone_desert_gravel",			fill="stone_sandstone_desert_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="stone_desert_gravel",						fill="stone_desert_gravel",				stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_cool_semiarid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_cool_semiarid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_dry",									fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dried",								fill="dirt_dried",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cold_humid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_snow",						fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_snow",						fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_snow",					fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_snow",						fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_snow",						fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_snow",						fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_snow",						fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_snow",						fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_snow",					fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cold_semihumid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_snow",						fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_snow",						fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_snow",					fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_snow",						fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_snow",						fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_snow",						fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_snow",						fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_snow",						fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_snow",					fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="rain",	top="dirt_with_litter_rainforest",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="conifer",	top="dirt_with_litter_coniferous",				fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cold_temperate = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_snow",						fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_snow",						fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_snow",					fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_snow",						fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_snow",						fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_snow",						fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_snow",						fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_snow",						fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_snow",					fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt",										fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry",									fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cold_semiarid = {
		n9	= {name="n9",		desc="black",	top="dirt_black_with_snow",		fill="dirt_black",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="dirt_brown_with_snow",		fill="dirt_brown",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey_with_snow",		fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy_with_snow",		fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="silt",	top="dirt_silt_01",								fill="dirt_silt_02",					stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="silty",	top="dirt_silty_with_snow",		fill="dirt_silty",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="dirt_sod_with_snow",	fill="dirt_sod",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="dirt_loam_with_snow",	fill="dirt_loam",						stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_snow",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_snow",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_with_snow",						fill="dirt",							stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dry_with_snow",					fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
	cold_arid = {
		n9	= {name="n9",		desc="black",	top="stone_sandstone_gravel",					fill="stone_sandstone_gravel",			stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n1	= {name="n1",		desc="brown",	top="stone_sandstone_white_gravel",				fill="stone_sandstone_white_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n10	= {name="n10",		desc="clay",	top="dirt_clay_red",							fill="dirt_clay_red",					stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n2	= {name="n2",		desc="clayey",	top="dirt_clayey",								fill="dirt_clayey",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n11	= {name="n11",		desc="sand",	top="sand",										fill="sand_desert",						stone="stone_desert",			river="gal:liquid_water_river_muddy_source",},
		n3	= {name="n3",		desc="sandy",	top="dirt_sandy",								fill="dirt_sandy",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n12	= {name="n12",		desc="desert",	top="sand_desert",								fill="sand_desert",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n4	= {name="n4",		desc="white",	top="sand_white",								fill="sand_white",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n13	= {name="n13",		desc="peat",	top="dirt_peat",								fill="dirt_peat",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n5	= {name="n5",		desc="mud",		top="dirt_mud_01",								fill="dirt_mud_02",						stone="stone_basalt_02",		river="gal:liquid_water_swamp_source",},
		n14	= {name="n14",		desc="sod",		top="stone_sandstone_desert_gravel",			fill="stone_sandstone_desert_gravel",	stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n6	= {name="n6",		desc="loam",	top="stone_desert_gravel",						fill="stone_desert_gravel",				stone="stone_basalt_01",		river="gal:liquid_water_dirty_source",},
		n15	= {name="n15",		desc="red",		top="dirt_red_with_grass_cool_semiarid_pale",	fill="dirt_red",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n7	= {name="n7",		desc="coarse",	top="dirt_coarse_with_grass_cool_semiarid",		fill="dirt_coarse",						stone="stone_basalt_01",		river="gal:liquid_water_river_muddy_source",},
		n16	= {name="n16",		desc="dry",		top="dirt_dry",									fill="dirt_dry",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
		n8	= {name="n8",		desc="drydry",	top="dirt_dried",								fill="dirt_dried",						stone="stone_basalt_01",		river="gal:liquid_water_swamp_source",},
	},
}
gal.ecosystems = {}

--
for b, bdef in pairs(eco_list) do

	--gal.ecosystems[bdef.name]								= {}
	gal.ecosystems[b]										= {}
	
	for e, edef in pairs(bdef) do

		gal.ecosystems[b][e]				= {}
		gal.ecosystems[b][e].name			= edef.name
		gal.ecosystems[b][e].top			= minetest.get_content_id("gal:" .. edef.top .. "")
		gal.ecosystems[b][e].fill			= minetest.get_content_id("gal:" .. edef.fill .. "")
		gal.ecosystems[b][e].stone			= minetest.get_content_id("gal:" .. edef.stone .. "")
		gal.ecosystems[b][e].river			= minetest.get_content_id("" .. edef.river .. "")
		
		--print(edef.name)
		--minetest.log(b .. ", " .. e)
		
	end
end
--



